//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonicNextRandomiser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonicNextRandomiser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonic the Hedgehog,sonic_new,true
        ///Sonic the Hedgehog (Mach Speed),sonic_fast,false
        ///Sonic the Hedgehog (Elise),princess,false
        ///Sonic the Hedgehog (White Acropolis Snowboard),snow_board_wap,false
        ///Sonic the Hedgehog (Crisis City Snowboard),snow_board,false
        ///Shadow the Hedgehog,shadow,true
        ///Silver the Hedgehog,silver,true
        ///Miles &quot;Tails&quot; Prower,tails,true
        ///Knuckles the Echidna,knuckles,true
        ///Rouge the Bat,rouge,true
        ///E-123 Omega,omega,true
        ///Blaze the Cat,blaze,true
        ///Amy Rose,amy,true.
        /// </summary>
        internal static string CharacterTypes {
            get {
                return ResourceManager.GetString("CharacterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WoodBox,WoodBox,true
        ///WoodBox_Prime,WoodBox_Prime,true
        ///WoodBox_Vs,WoodBox_Vs,true
        ///WoodBoxBrk,WoodBoxBrk,false
        ///ReinforcedWoodBox,ReinforcedWoodBox,true
        ///IronBox,IronBox,true
        ///IronBox_Prime,IronBox_Prime,true
        ///IronBox_Vs,IronBox_Vs,true
        ///IronBoxBrk,IronBoxBrk,false
        ///BrickWall,BrickWall,true
        ///BombBox,BombBox,true
        ///BombBox_Prime,BombBox_Prime,true
        ///BombBox_Vs,BombBox_Vs,true
        ///BombBoxBrk,BombBoxBrk,false
        ///FlashBox,FlashBox,true
        ///FlashBox_Prime,FlashBox_Prime,true
        ///FlashBox_Vs,FlashBox_Vs,true
        ///FlashBoxBrk,Fla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommonPropTypes {
            get {
                return ResourceManager.GetString("CommonPropTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic Base,aqa_door,True
        ///Dusty Desert,dtd_door,True
        ///Flame Core,flc_door,True
        ///Kingdom Valley,kdv_door,True
        ///Radical Train,rct_door,True
        ///White Acropolis,wap_door,True
        ///Wave Ocean (Small),wvo_doorA,True
        ///Wave Ocean (Large),wvo_doorB,True.
        /// </summary>
        internal static string DoorTypes {
            get {
                return ResourceManager.GetString("DoorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iblis Biter,cBiter,true
        ///Iblis Golem,cGolem,true
        ///Iblis Taker,cTaker,true
        ///Iblis Worm,cCrawler,true
        ///Mephiles Gazer,cGazer,true
        ///Mephiles Stalker,cStalker,true
        ///Mephiles Titan,cTitan,true
        ///Mephiles Tricker,cTricker,true
        ///Egg Armour,eArmor,true
        ///Egg Buster,eBluster,true
        ///Egg Buster (Egg Gunner),eBuster,true
        ///Egg Buster (Egg Gunner) (Fly),eBuster(Fly),true
        ///Egg Bomber,eBomber,true
        ///Egg Cannon,eCannon,true
        ///Egg Cannon (Fly),eCannon(Fly),true
        ///Egg Chaser,eChaser,true
        ///Egg Commander,eCommander,true
        ///Egg Flyer,eF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnemyTypes {
            get {
                return ResourceManager.GetString("EnemyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic Base,stage/aqa/a/aqa_envmap.dds,true
        ///Crisis City (Original),stage/csc/a/csc_envmap.dds,true
        ///Crisis City (Filtered),stage/csc/b/csc_envmap.dds,true
        ///Crisis City (End of the World),stage/end/a/endA_envmap.dds,true
        ///Dusty Desert (Outside),stage/dtd/a/suna_cube.dds,true
        ///Dusty Desert (Inside),stage/dtd/b/suna_cube.dds,true
        ///Dusty Desert (Mephiles),stage/boss/secondmefiress_dtd/suna_cube.dds,true
        ///Dusty Desert (End of the World),stage/end/d/endD_envmap.dds,true
        ///End of the World,stage/boss/solaris_last [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnvMaps {
            get {
                return ResourceManager.GetString("EnvMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Event] The Chaos Emeralds entrusted,scripts/stage/event/scene_e0031.lub,True
        ///[Event] Meeting with Tails,scripts/stage/event/scene_e0001.lub,True
        ///[Event] Too late Sonic,scripts/stage/event/scene_e0002.lub,True
        ///[Event] Sonic Rescues Elise,scripts/stage/event/scene_e0003.lub,True
        ///[Event] Let&apos;s Split Up,scripts/stage/event/scene_e0004.lub,True
        ///[Event] Silver appears,scripts/stage/event/scene_e0006.lub,True
        ///[Event] Saved by Amy,scripts/stage/event/scene_e0007.lub,True
        ///[Event] Eggman sends Sonic to the fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventLighting {
            get {
                return ResourceManager.GetString("EventLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquatic Base A,stage/aqa/a,True
        ///Aquatic Base B,stage/aqa/b,True
        ///Aquatic Base Hanger,stage/event/ev0028,True
        ///Aquatic Base Sealing Chamber,stage/event/ev0221,True
        ///Crisis City A,stage/csc/a,True
        ///Crisis City B,stage/csc/b,True
        ///Crisis City C,stage/csc/c,True
        ///Crisis City E,stage/csc/e,True
        ///Crisis City F,stage/csc/f,True
        ///Crisis City Arena,stage/csc/iblis01,True
        ///Crisis City Computer Room,stage/event/ev0106,True
        ///Crisis City Database,stage/event/ev0012,True
        ///Crisis City Overlook,stage/event/ev0105,True
        ///Du [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventTerrain {
            get {
                return ResourceManager.GetString("EventTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Rings,1,true
        ///10 Rings,2,true
        ///20 Rings,3,true
        ///Extra Life,4,true
        ///Power Sneakers,5,true
        ///Gauge Refill,6,true
        ///Invincibility,7,true
        ///Shield,8,true.
        /// </summary>
        internal static string ItemTypes {
            get {
                return ResourceManager.GetString("ItemTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English,e,True
        ///French,f,False
        ///German,g,False
        ///Italian,i,False
        ///Japanese,j,False
        ///Spanish,s,False.
        /// </summary>
        internal static string MiscLanguages {
            get {
                return ResourceManager.GetString("MiscLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Ocean - The Water&apos;s Edge,stg_wvo_a,True
        ///Wave Ocean - The Inlet,stg_wvo_b,True
        ///Dusty Desert - Quicksand,stg_dtd_a,True
        ///Dusty Desert - The Ruins,stg_dtd_b,True
        ///White Acropolis - Snowy Peak,stg_wap_a,True
        ///White Acropolis - The Base,stg_wap_b,True
        ///Crisis City - The Flames,stg_csc_a,True
        ///Crisis City - Skyscraper,stg_csc_b,True
        ///Crisis City - Whirlwind,stage_csc_e,True
        ///Crisis City - Tornado,stg_csc_f,True
        ///Flame Core - Volcano,stg_flc_a,True
        ///Flame Core - The Cavern,stg_flc_b,True
        ///Radical Train - Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MiscSongs {
            get {
                return ResourceManager.GetString("MiscSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DtdBat1,DtdBat1,True
        ///DtdBat2,DtdBat2,True
        ///DtdBat3,DtdBat3,True
        ///AqaDolphin1,AqaDolphin1,True
        ///AqaDolphin2,AqaDolphin2,True
        ///AqaTurtle,AqaTurtle,True
        ///AqaFishA01,AqaFishA01,True
        ///AqaFishA02,AqaFishA02,True
        ///AqaManta,AqaManta,True
        ///AqaManta02,AqaManta02,True
        ///WvoSeagull1,WvoSeagull1,True
        ///WvoDolphin1,WvoDolphin1,True
        ///WvoDolphin2,WvoDolphin2,True
        ///TwnWell,TwnWell,True
        ///TwnTreeA,TwnTreeA,True
        ///TwnPillar_red,TwnPillar_red,True
        ///TwnPillar_blue,TwnPillar_blue,True
        ///TwnPillar_blue_s,TwnPillar_blue_s,True
        ///TwnFlo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PathPropTypes {
            get {
                return ResourceManager.GetString("PathPropTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hint_all01_a00_sn,hint_all01_a00_sn,True
        ///hint_all01_a00_tl,hint_all01_a00_tl,True
        ///hint_all01_a00_kn,hint_all01_a00_kn,True
        ///hint_all01_a00_sd,hint_all01_a00_sd,True
        ///hint_all01_a00_rg,hint_all01_a00_rg,True
        ///hint_all01_a00_om,hint_all01_a00_om,True
        ///hint_all01_a00_am,hint_all01_a00_am,True
        ///hint_all01_a00_bz,hint_all01_a00_bz,True
        ///hint_all01_a00_sv,hint_all01_a00_sv,True
        ///hint_all01_a00_pr,hint_all01_a00_pr,True
        ///hint_all01_a01_sn,hint_all01_a01_sn,True
        ///hint_all01_a01_tl,hint_all01_a01_tl,True
        ///hint_all [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VoiceTypes {
            get {
                return ResourceManager.GetString("VoiceTypes", resourceCulture);
            }
        }
    }
}
