//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONIC_THE_HEDGEHOG__2006__Randomiser_Suite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SONIC_THE_HEDGEHOG__2006__Randomiser_Suite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hint_all01_a00_tl
        ///hint_all01_a00_kn
        ///hint_all01_a00_sd
        ///hint_all01_a00_rg
        ///hint_all01_a00_om
        ///hint_all01_a00_am
        ///hint_all01_a00_bz
        ///hint_all01_a00_sv
        ///hint_all01_a00_pr
        ///hint_all01_a01_sn
        ///hint_all01_a01_tl
        ///hint_all01_a01_kn
        ///hint_all01_a01_sd
        ///hint_all01_a01_rg
        ///hint_all01_a01_om
        ///hint_all01_a01_am
        ///hint_all01_a01_bz
        ///hint_all01_a01_sv
        ///hint_all01_a01_pr
        ///hint_all01_a02_sn
        ///hint_all01_a02_tl
        ///hint_all01_a02_kn
        ///hint_all01_a02_sd
        ///hint_all01_a02_rg
        ///hint_all01_a02_om
        ///hint_all01_a02_am
        ///hint_all01_a02_bz        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s06TextStrings {
            get {
                return ResourceManager.GetString("s06TextStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seedIcon {
            get {
                object obj = ResourceManager.GetObject("seedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
