//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SONIC_THE_HEDGEHOG__2006__Randomiser_Suite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SONIC_THE_HEDGEHOG__2006__Randomiser_Suite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aqa_floor01
        ///aqa_floor02
        ///aqa_floor03
        ///aqa_floor04
        ///aqa_floor05
        ///aqa_foothold
        ///billboard
        ///bldgwaste_a
        ///bldgwaste_b
        ///bldgwaste_c
        ///BombBox
        ///BombBox_Prime
        ///BombBox_Vs
        ///cmn_barrel_b_a
        ///cmn_barrel_s_a
        ///cmn_chair_a
        ///cmn_drumA
        ///cmn_drumB
        ///cmn_tableA
        ///container
        ///container_d
        ///csc_breakroad
        ///csc_breakroad_no
        ///csc_breakwall
        ///csc_breakwall_d
        ///csc_breakwall_esp
        ///csc_breakwall02
        ///csc_rock
        ///csc_rock_d
        ///csc_tank
        ///csc_tank_base
        ///csc_tank_d
        ///csc_tank2
        ///debrisA_h
        ///debrisB
        ///debrisB_br
        ///debrisB_h
        ///dtd_breakwall
        ///dtd_obj_statue        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s06PhysicsObjects {
            get {
                return ResourceManager.GetString("s06PhysicsObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hint_all01_a00_sn
        ///hint_all01_a00_tl
        ///hint_all01_a00_kn
        ///hint_all01_a00_sd
        ///hint_all01_a00_rg
        ///hint_all01_a00_om
        ///hint_all01_a00_am
        ///hint_all01_a00_bz
        ///hint_all01_a00_sv
        ///hint_all01_a00_pr
        ///hint_all01_a01_sn
        ///hint_all01_a01_tl
        ///hint_all01_a01_kn
        ///hint_all01_a01_sd
        ///hint_all01_a01_rg
        ///hint_all01_a01_om
        ///hint_all01_a01_am
        ///hint_all01_a01_bz
        ///hint_all01_a01_sv
        ///hint_all01_a01_pr
        ///hint_all01_a02_sn
        ///hint_all01_a02_tl
        ///hint_all01_a02_kn
        ///hint_all01_a02_sd
        ///hint_all01_a02_rg
        ///hint_all01_a02_om
        ///hint_all01_a02_am        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s06TextStrings {
            get {
                return ResourceManager.GetString("s06TextStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seedIcon {
            get {
                object obj = ResourceManager.GetObject("seedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
