//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonic_06_Randomiser_Suite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonic_06_Randomiser_Suite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] arctool {
            get {
                object obj = ResourceManager.GetObject("arctool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cBiter_Fix
        ///cBiter_Freeze
        ///cBiter_Normal
        ///cBiter_Wall_Fix
        ///cBiter_Wall_Normal.
        /// </summary>
        internal static string cBiterParams {
            get {
                return ResourceManager.GetString("cBiterParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cCrawler_Alarm
        ///cCrawler_Fix
        ///cCrawler_Freeze
        ///cCrawler_Normal
        ///cCrawler_Wall_Fix
        ///cCrawler_Wall_Homing.
        /// </summary>
        internal static string cCrawlerParams {
            get {
                return ResourceManager.GetString("cCrawlerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cGazer_Alarm
        ///cGazer_Fix
        ///cGazer_Freeze
        ///cGazer_Normal
        ///cGazer_Wall_Fix.
        /// </summary>
        internal static string cGazerParams {
            get {
                return ResourceManager.GetString("cGazerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cGolem_Alarm
        ///cGolem_Fix
        ///cGolem_Freeze
        ///cGolem_Normal.
        /// </summary>
        internal static string cGolemParams {
            get {
                return ResourceManager.GetString("cGolemParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cStalker_Fix
        ///cStalker_Freeze
        ///cStalker_Normal
        ///cStalker_Wall_Fix
        ///cStalker_Wall_Normal.
        /// </summary>
        internal static string cStalkerParams {
            get {
                return ResourceManager.GetString("cStalkerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cTaker_Chase_Bomb
        ///cTaker_Fix
        ///cTaker_Fix_Bomb
        ///cTaker_Homing
        ///cTaker_Normal
        ///cTaker_Normal_Bomb.
        /// </summary>
        internal static string cTakerParams {
            get {
                return ResourceManager.GetString("cTakerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cTitan_Alarm
        ///cTitan_Fix
        ///cTitan_Freeze
        ///cTitan_Normal.
        /// </summary>
        internal static string cTitanParams {
            get {
                return ResourceManager.GetString("cTitanParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cTricker_Alarm
        ///cTricker_Fix
        ///cTricker_Homing
        ///cTricker_Master
        ///cTricker_Normal
        ///cTricker_Slave.
        /// </summary>
        internal static string cTrickerParams {
            get {
                return ResourceManager.GetString("cTrickerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eArmor_Fix
        ///eArmor_Normal.
        /// </summary>
        internal static string eArmorParams {
            get {
                return ResourceManager.GetString("eArmorParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eBluster_Fix
        ///eBluster_Homing
        ///eBluster_Normal.
        /// </summary>
        internal static string eBlusterParams {
            get {
                return ResourceManager.GetString("eBlusterParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eBomber_Allaround
        ///eBomber_Boss
        ///eBomber_Fix
        ///eBomber_Normal
        ///eBomber_Wall_Fix
        ///eBomber_Wall_Normal.
        /// </summary>
        internal static string eBomberParams {
            get {
                return ResourceManager.GetString("eBomberParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eBusterFly_Fix
        ///eBusterFly_Normal
        ///eBusterFly_Trans.
        /// </summary>
        internal static string eBusterFlyParams {
            get {
                return ResourceManager.GetString("eBusterFlyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eBuster_Fix
        ///eBuster_Normal
        ///eBuster_Trans.
        /// </summary>
        internal static string eBusterParams {
            get {
                return ResourceManager.GetString("eBusterParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCannonFly_Carrier
        ///eCannonFly_Fix
        ///eCannonFly_Normal
        ///eCannonFly_Trans.
        /// </summary>
        internal static string eCannonFlyParams {
            get {
                return ResourceManager.GetString("eCannonFlyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCannon_Fix
        ///eCannon_Fix_Laser
        ///eCannon_Fix_Launcher
        ///eCannon_Normal
        ///eCannon_Trans
        ///eCannon_Wall_Fix.
        /// </summary>
        internal static string eCannonParams {
            get {
                return ResourceManager.GetString("eCannonParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCerberus_shadow
        ///eCerberus_sonic.
        /// </summary>
        internal static string eCerberusParams {
            get {
                return ResourceManager.GetString("eCerberusParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eChaser_Alarm
        ///eChaser_Chase
        ///eChaser_Master
        ///eChaser_Normal.
        /// </summary>
        internal static string eChaserParams {
            get {
                return ResourceManager.GetString("eChaserParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCommander_Alarm
        ///eCommander_Fix
        ///eCommander_Master
        ///eCommander_Normal.
        /// </summary>
        internal static string eCommanderParams {
            get {
                return ResourceManager.GetString("eCommanderParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eFlyer_Boss_Homing
        ///eFlyer_Boss_Vulcan
        ///eFlyer_Fix
        ///eFlyer_Fix_Rocket
        ///eFlyer_Fix_Vulcan
        ///eFlyer_Homing
        ///eFlyer_Normal.
        /// </summary>
        internal static string eFlyerParams {
            get {
                return ResourceManager.GetString("eFlyerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eGenesis_silver
        ///eGenesis_sonic.
        /// </summary>
        internal static string eGenesisParams {
            get {
                return ResourceManager.GetString("eGenesisParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eGuardian_Ball_Fix
        ///eGuardian_Ball_Normal
        ///eGuardian_Fix
        ///eGuardian_Freeze
        ///eGuardian_Normal.
        /// </summary>
        internal static string eGuardianParams {
            get {
                return ResourceManager.GetString("eGuardianParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eGunnerFly_Chase
        ///eGunnerFly_Fix
        ///eGunnerFly_Fix_Rocket
        ///eGunnerFly_Fix_Vulcan
        ///eGunnerFly_Homing
        ///eGunnerFly_Normal
        ///eGunnerFly_Trans.
        /// </summary>
        internal static string eGunnerFlyParams {
            get {
                return ResourceManager.GetString("eGunnerFlyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eGunner_Chase
        ///eGunner_Fix
        ///eGunner_Fix_Rocket
        ///eGunner_Fix_Vulcan
        ///eGunner_Normal
        ///eGunner_Trans.
        /// </summary>
        internal static string eGunnerParams {
            get {
                return ResourceManager.GetString("eGunnerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eHunter_Fix
        ///eHunter_Hide_Fix
        ///eHunter_Normal.
        /// </summary>
        internal static string eHunterParams {
            get {
                return ResourceManager.GetString("eHunterParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eKeeper_Ball_Fix
        ///eKeeper_Fix
        ///eKeeper_Freeze
        ///eKeeper_Normal.
        /// </summary>
        internal static string eKeeperParams {
            get {
                return ResourceManager.GetString("eKeeperParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eLancerFly_Chase
        ///eLancerFly_Fix
        ///eLancerFly_Fix_Laser
        ///eLancerFly_Normal
        ///eLancerFly_Trans.
        /// </summary>
        internal static string eLancerFlyParams {
            get {
                return ResourceManager.GetString("eLancerFlyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eLancer_Fix
        ///eLancer_Normal
        ///eLancer_Trans.
        /// </summary>
        internal static string eLancerParams {
            get {
                return ResourceManager.GetString("eLancerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eLiner_Chase
        ///eLiner_Normal
        ///eLiner_Slave.
        /// </summary>
        internal static string eLinerParams {
            get {
                return ResourceManager.GetString("eLinerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eRounder_Fix
        ///eRounder_Normal
        ///eRounder_Slave
        ///eRounder_Twn_Chase
        ///eRounder_Twn_Escape.
        /// </summary>
        internal static string eRounderParams {
            get {
                return ResourceManager.GetString("eRounderParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSearcher_Alarm
        ///eSearcher_Fix
        ///eSearcher_Fix_Bomb
        ///eSearcher_Fix_Rocket
        ///eSearcher_Normal.
        /// </summary>
        internal static string eSearcherParams {
            get {
                return ResourceManager.GetString("eSearcherParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eStingerFly_Chase
        ///eStingerFly_Fix
        ///eStingerFly_Fix_Missile
        ///eStingerFly_Homing
        ///eStingerFly_Normal.
        /// </summary>
        internal static string eStingerFlyParams {
            get {
                return ResourceManager.GetString("eStingerFlyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eStinger_Chase
        ///eStinger_Fix
        ///eStinger_Fix_Missile
        ///eStinger_Normal
        ///eStinger_Trans.
        /// </summary>
        internal static string eStingerParams {
            get {
                return ResourceManager.GetString("eStingerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eSweeper_Fix
        ///eSweeper_Wall_Fix.
        /// </summary>
        internal static string eSweeperParams {
            get {
                return ResourceManager.GetString("eSweeperParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWalker_Fix
        ///eWalker_Normal.
        /// </summary>
        internal static string eWalkerParams {
            get {
                return ResourceManager.GetString("eWalkerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eWyvern.
        /// </summary>
        internal static string eWyvernParams {
            get {
                return ResourceManager.GetString("eWyvernParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstIblis.
        /// </summary>
        internal static string firstIblisParams {
            get {
                return ResourceManager.GetString("firstIblisParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstmefiress_omega
        ///firstmefiress_shadow.
        /// </summary>
        internal static string firstmefiressParams {
            get {
                return ResourceManager.GetString("firstmefiressParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo1 {
            get {
                object obj = ResourceManager.GetObject("Logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aqa_floor01
        ///aqa_floor02
        ///aqa_floor03
        ///aqa_floor04
        ///aqa_floor05
        ///aqa_foothold
        ///billboard
        ///bldgwaste_a
        ///bldgwaste_b
        ///bldgwaste_c
        ///BombBox
        ///BombBox_Prime
        ///BombBox_Vs
        ///cmn_barrel_b_a
        ///cmn_barrel_s_a
        ///cmn_chair_a
        ///cmn_drumA
        ///cmn_drumB
        ///cmn_tableA
        ///container
        ///container_d
        ///csc_breakroad
        ///csc_breakroad_no
        ///csc_breakwall
        ///csc_breakwall_d
        ///csc_breakwall_esp
        ///csc_breakwall02
        ///csc_rock
        ///csc_rock_d
        ///csc_tank
        ///csc_tank_base
        ///csc_tank_d
        ///csc_tank2
        ///debrisA_h
        ///debrisB
        ///debrisB_br
        ///debrisB_h
        ///dtd_breakwall
        ///dtd_obj_statue
        ///dtd_obj_statue_fix
        ///dtd_obj_statue_mefi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S06PhysicsObjects {
            get {
                return ResourceManager.GetString("S06PhysicsObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hint_all01_a00_sn
        ///hint_all01_a00_tl
        ///hint_all01_a00_kn
        ///hint_all01_a00_sd
        ///hint_all01_a00_rg
        ///hint_all01_a00_om
        ///hint_all01_a00_am
        ///hint_all01_a00_bz
        ///hint_all01_a00_sv
        ///hint_all01_a00_pr
        ///hint_all01_a01_sn
        ///hint_all01_a01_tl
        ///hint_all01_a01_kn
        ///hint_all01_a01_sd
        ///hint_all01_a01_rg
        ///hint_all01_a01_om
        ///hint_all01_a01_am
        ///hint_all01_a01_bz
        ///hint_all01_a01_sv
        ///hint_all01_a01_pr
        ///hint_all01_a02_sn
        ///hint_all01_a02_tl
        ///hint_all01_a02_kn
        ///hint_all01_a02_sd
        ///hint_all01_a02_rg
        ///hint_all01_a02_om
        ///hint_all01_a02_am
        ///hint_all01_a02_bz
        ///hint_all [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string S06TextStrings {
            get {
                return ResourceManager.GetString("S06TextStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secondIblis_shadow
        ///secondIblis_sonic.
        /// </summary>
        internal static string secondIblisParams {
            get {
                return ResourceManager.GetString("secondIblisParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seed {
            get {
                object obj = ResourceManager.GetObject("Seed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solaris01.
        /// </summary>
        internal static string solaris01Params {
            get {
                return ResourceManager.GetString("solaris01Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to solaris02.
        /// </summary>
        internal static string solaris02Params {
            get {
                return ResourceManager.GetString("solaris02Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirdIblis.
        /// </summary>
        internal static string thirdIblisParams {
            get {
                return ResourceManager.GetString("thirdIblisParams", resourceCulture);
            }
        }
    }
}
